remove vm connect from action

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -45,14 +45,14 @@ jobs:
       - name: Install Yandex Cloud CLI
         run: |
           curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
-          export PATH="$HOME/yandex-cloud/bin:$PATH"
           echo "PATH=$PATH"
-          yc --version
+          echo "Checking yc version"
+          yc --version || echo "yc command not found, check PATH"
 
       - name: Configure Yandex Cloud CLI
         run: |
           echo "${{ secrets.YANDEX_CLOUD_OAUTH_TOKEN }}" > /home/runner/yc-token
-          yc config set token $(cat /home/runner/yc-token)
+          yc config set token $(cat /home/runner/yc-token) || echo "Failed to configure yc CLI"
 
       - name: Update Docker Image Tag in Kubernetes Manifest
         run: |
@@ -61,8 +61,9 @@ jobs:
       - name: Apply Kubernetes Secrets
         run: |
           export PATH="$HOME/yandex-cloud/bin:$PATH"
+          echo "PATH=$PATH"
           yc --version
-          yc managed-kubernetes cluster get-credentials --id cat6mq8u5ndujs9rqrde --external --force
+          yc managed-kubernetes cluster get-credentials --id cat6mq8u5ndujs9rqrde --external --force || echo "Failed to get credentials"
           kubectl create secret generic db-secrets \
             --from-literal=redis_connection=${{ secrets.REDIS_CONNECTION }} \
             --from-literal=redis_host=${{ secrets.REDIS_HOST }} \
